### ISSUE TITLE
High Sierra install bugs

### ISSUE THREAD

**Issue by pwolfram** [pwolfram/homebrew-mpas#4]
From @tpeterka:

Here are the errors I got when I tried your homebrew install on the latest mac high sierra 10.13.3

-----
```
brew tap homebrew/science
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.

brew tap pwolfram/mpas
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!

brew install pwolfram/mpas/netcdf --enable-fortran --enable-cxx-compat
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/netcdf.rb:8:in `<class:Netcdf>'
Please report this to the pwolfram/mpas tap!

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
```
-----

Also, here are the version numbers for my linux build:
```
export NETCDF="/homes/tpeterka/software/netcdf-4.4.1.1/build"
export PNETCDF="/homes/tpeterka/software/parallel-netcdf-1.8.1"
export PIO="/homes/tpeterka/software/ParallelIO-pio2_2_1/install"
export CORE=ocean
export USE_PIO2=true
export MODE=forward
```

**Comment by pwolfram** [comment]
Thanks for reporting @tpeterka.  I know you have a work-around now for the short term, but please let me know if this issue becomes a bottleneck for you.  Thanks!

**Comment by fprimeau** [comment]
I'm having the same problem as @tpeterka on save mac OS (mac high sierra 10.13.3).  I would love to know about the work-around. Thanks. 

The error listing is given below. I did try adding "$HOME/.linuxbrew/bin:$PATH" to $PATH, but got the same error. 
THanks


ocean:RESEARCH fprimeau$ cd homebrew-mpas/
ocean:homebrew-mpas fprimeau$ ls
README.md          netcdf.rb          pio.rb
install.sh         parallel-netcdf.rb
ocean:homebrew-mpas fprimeau$ chmod +x install.sh
ocean:homebrew-mpas fprimeau$ ./install.sh
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/Users/fprimeau/Library/Caches/Homebrew/
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
Password:
==> /usr/bin/sudo /bin/chown fprimeau /Library/Caches/Homebrew
sudo: /bin/chown: command not found
Failed during: /usr/bin/sudo /bin/chown fprimeau /Library/Caches/Homebrew
Must add "$HOME/.linuxbrew/bin:$PATH" to $PATH
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/netcdf.rb
Calling 'depends_on :fortran' is disabled!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/netcdf.rb:8:in `<class:Netcdf>'
Please report this to the pwolfram/mpas tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
Error: No available formula with the name "open-mpi@1.6"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Warning: Error searching on GitHub: GitHub
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"

Error: No formulae found in taps.
Error: No such keg: /usr/local/Cellar/open-mpi@1.6
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Reinstalling nco
==> Downloading https://downloads.sourceforge.net/project/nco/nco-4.7.4.tar.gz
Already downloaded: /Users/fprimeau/Library/Caches/Homebrew/nco-4.7.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nco/4.7.4_1 --enable-netcdf4
==> make install
Warning: nco dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/nco/4.7.4_1: 52 files, 10.4MB, built in 49 seconds
Warning: llvm 6.0.0 is already installed and up-to-date
To reinstall 6.0.0, run `brew reinstall llvm`
Warning: metis 5.1.0 is already installed and up-to-date
To reinstall 5.1.0, run `brew reinstall metis`
Warning: wget 1.19.5 is already installed, it's just not linked
You can use `brew link wget` to link this version.
ocean:homebrew-mpas fprimeau$

**Comment by pwolfram** [comment]
@fprimeau, do you get the same error message?  Do you mind posting it if only for completeness?

I'm on just Sierra right now so debugging this is hard without going through the update process, which I don't have time to do right now in the short term.  I'm happy to try to help, however, if I can see some direct fix.

**Comment by fprimeau** [comment]
My error message are not completely the same.  My error listings are given below. I did try adding "$HOME/.linuxbrew/bin/$PATH" in a second attempt, but got the same error. 
Thank you for any help you might provide. 

ocean:homebrew-mpas fprimeau$ ./install.sh
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/Users/fprimeau/Library/Caches/Homebrew/
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
Password:
==> /usr/bin/sudo /bin/chown fprimeau /Library/Caches/Homebrew
sudo: /bin/chown: command not found
Failed during: /usr/bin/sudo /bin/chown fprimeau /Library/Caches/Homebrew
Must add "$HOME/.linuxbrew/bin:$PATH" to $PATH
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/netcdf.rb
Calling 'depends_on :fortran' is disabled!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/netcdf.rb:8:in `<class:Netcdf>'
Please report this to the pwolfram/mpas tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
Error: No available formula with the name "open-mpi@1.6"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Warning: Error searching on GitHub: GitHub
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"

Error: No formulae found in taps.
Error: No such keg: /usr/local/Cellar/open-mpi@1.6
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Tapping pwolfram/mpas
Cloning into '/usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pwolfram/homebrew-mpas/parallel-netcdf.rb
Unsupported special dependency :"open-mpi@1.6"
Error: Cannot tap pwolfram/mpas: invalid syntax in tap!
==> Reinstalling nco
==> Downloading https://downloads.sourceforge.net/project/nco/nco-4.7.4.tar.gz
Already downloaded: /Users/fprimeau/Library/Caches/Homebrew/nco-4.7.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nco/4.7.4_1 --enable-netcdf4
==> make install
Warning: nco dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/nco/4.7.4_1: 52 files, 10.4MB, built in 49 seconds
Warning: llvm 6.0.0 is already installed and up-to-date
To reinstall 6.0.0, run `brew reinstall llvm`
Warning: metis 5.1.0 is already installed and up-to-date
To reinstall 5.1.0, run `brew reinstall metis`
Warning: wget 1.19.5 is already installed, it's just not linked
You can use `brew link wget` to link this version.

**Comment by pwolfram** [comment]
Thanks @fprimeau!  Hopefully I'll have some type of solution in the next several weeks.  @sbrus89 will need it too as he spins up also.  We'll all work on it together.

**Comment by pwolfram** [comment]
Hi Everyone!

I've pushed some changes that should allow you all to build on High Sierra.  I've confirmed this works on my High Sierra build.  It should also work on Sierra too. Please feel free to test the new workflow and let me know if it works.  I confirmed it works with the nightly test suite.

Thanks!
Phil
